### get all users 
http://localhost:5001/users

### create user

POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
    "name": "duy tran 3333",
    "age": "37"
}

### get user

http://localhost:5000/users/1

### get invalid user

http://localhost:5001/users/1234

### update user 1

PATCH http://localhost:5000/users/1 HTTP/1.1
content-type: application/json

{
    "name": "duy tran - updated",
    "age": "37"
}

### update invalid user

PATCH http://localhost:5001/users/1234 HTTP/1.1
content-type: application/json

{
    "name": "duy tran - updated",
    "age": "37"
}


### delete user

DELETE http://localhost:5001/users/3


### not found route
http://localhost:5001/not-found