### get all users 5001/api/users

http://localhost:5001/api/users?param1=a&param2=b

### create user

POST http://localhost:5001/api/users HTTP/1.1
content-type: application/json

{
    "name": "duy 233",
    "email": "duy222@test.vn",
    "password": "1234",
    "phone": "123456789",
    "age": 333
}

### get user

http://localhost:5001/api/users/664360bf84a02f5edcc2d430

### get invalid user

http://localhost:5001/api/users/1234

### update user 1

PATCH http://localhost:5001/api/users/664360bf84a02f5edcc2d430 HTTP/1.1
content-type: application/json

{
    "name": "duy tran - updated",
    "email": "duy-updated@test.vn"
}

### update invalid user

PATCH http://localhost:5001/api/users/1234 HTTP/1.1
content-type: application/json

{
    "name": "duy tran - updated",
    "age": "37"
}


### delete user
DELETE http://localhost:5001/api/users/66434d633706192929d98c10

### find by email

http://localhost:5001/api/users/duy@test.vn


### find by password

http://localhost:5001/api/users/password/1234


### not found route
http://localhost:5001/not-found


### form to create user

PATCH http://localhost:5001/api/users/664360bf84a02f5edcc2d430 HTTP/1.1
content-type: application/json

{
    "name": "duy tran - updated",
    "email": "duy-updated@test.vn"
}